export const SWAP_BASKET_ACTIVE = 'SWAP_BASKET_ACTIVE';
export const DISCORD_ACTIVE = 'DISCORD_ACTIVE';
export const WALLET_ACTIVE = 'WALLET_ACTIVE';
export const REVIEW_ACTIVE = 'REVIEW_ACTIVE';
export const ANIMATING_TRADE = 'ANIMATING_TRADE';
export const VIEW_POSITION = 'VIEW_POSITION';

export const VIEW_BASKET_LEFT = 'VIEW_BASKET_LEFT';
export const VIEW_BASKET_RIGHT = 'VIEW_BASKET_RIGHT';
export const VIEW_WALLET = 'VIEW_WALLET';
export const VIEW_SWAP = 'VIEW_SWAP';
export const VIEW_REVIEW = 'VIEW_REVIEW';

export const ANIMATING_SWAP = 'ANIMATING_SWAP';
export const POPOVER_ACTIVE = 'POPOVER_ACTIVE';
export const POPOVER_REF = 'POPOVER_REF';
export const POPOVER_CHILDREN = 'POPOVER_CHILDREN';
export const POPOVER_ADD = 'POPOVER_ADD';

export const PROXY_CONNECT_WALLET = 'PROXY_CONNECT_WALLET';
export const PROXY_LIST = 'PROXY_LIST';

const bubbles = {
  SWAP_BASKET_ACTIVE,
  DISCORD_ACTIVE,
  WALLET_ACTIVE,
  ANIMATING_TRADE,
  VIEW_POSITION,
  VIEW_BASKET_LEFT,
  VIEW_BASKET_RIGHT,
  VIEW_WALLET,
  VIEW_SWAP,
  VIEW_REVIEW,
  POPOVER_ADD,
  ANIMATING_SWAP,
  PROXY_LIST,
};

export default bubbles;
